<a href="https://colab.research.google.com/github/LUISTHOMAS77/projeto_aplicado/blob/main/PROJETO_APLICADO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import glob

# Defina o caminho onde estão seus CSVs no Drive.
# O asterisco (*) faz com que ele pegue todos os arquivos .csv da pasta.
caminho_arquivos = '/content/drive/MyDrive/dados/*.csv'
lista_arquivos = glob.glob(caminho_arquivos)

# Lista vazia para guardar os dataframes filtrados
dataframes_filtrados = []

# Variáveis para você ajustar conforme sua necessidade
coluna_para_filtrar = 'CD_OPERADORA'
valor_do_filtro = '352501'

for arquivo in lista_arquivos:
    print(f"Processando: {arquivo}")

    # Lê o CSV. Se der erro de codificação, adicione encoding='latin1' ou 'utf-8'
    df_temp = pd.read_csv(arquivo)

    # Aplica o filtro imediatamente para economizar RAM
    df_temp_filtrado = df_temp[df_temp[coluna_para_filtrar] == valor_do_filtro]

    # Adiciona o resultado filtrado na lista
    dataframes_filtrados.append(df_temp_filtrado)

# Junta todos os dataframes filtrados em um único
df_final = pd.concat(dataframes_filtrados, ignore_index=True)
print(f"Total de linhas após o filtro: {len(df_final)}")

Processando: /content/drive/MyDrive/dados/pda-024-icb-RS-2025_07.csv

ParserError: Error tokenizing data. C error: Expected 2 fields in line 208, saw 3

In [ ]:
import pandas as pd
import glob

# Caminho dos arquivos CSV
caminho_arquivos = '/content/drive/MyDrive/dados/*.csv'
lista_arquivos = glob.glob(caminho_arquivos)

dataframes_filtrados = []

# Definição do filtro
coluna_para_filtrar = 'CD_OPERADORA'
valor_do_filtro = '352501'

for arquivo in lista_arquivos:
    print(f"Processando: {arquivo}")

    # Define o separador como ponto e vírgula (sep=';') e a codificação (encoding='latin1')
    df_temp = pd.read_csv(arquivo, sep=';', encoding='latin1', low_memory=False)

    # Converte a coluna para texto para evitar incompatibilidade de tipos
    df_temp[coluna_para_filtrar] = df_temp[coluna_para_filtrar].astype(str)

    # Aplica o filtro
    df_temp_filtrado = df_temp[df_temp[coluna_para_filtrar] == valor_do_filtro]

    dataframes_filtrados.append(df_temp_filtrado)

# Junta todos os dataframes filtrados em um único
df_final = pd.concat(dataframes_filtrados, ignore_index=True)
print(f"Total de linhas após o filtro: {len(df_final)}")

Processando: /content/drive/MyDrive/dados/pda-024-icb-RS-2025_07.csv
Processando: /content/drive/MyDrive/dados/pda-024-icb-RS-2025_01.csv
Processando: /content/drive/MyDrive/dados/pda-024-icb-RS-2025_02.csv
Processando: /content/drive/MyDrive/dados/pda-024-icb-RS-2025_03.csv
Processando: /content/drive/MyDrive/dados/pda-024-icb-RS-2025_04.csv
Processando: /content/drive/MyDrive/dados/pda-024-icb-RS-2025_05.csv
Processando: /content/drive/MyDrive/dados/pda-024-icb-RS-2025_06.csv
Processando: /content/drive/MyDrive/dados/pda-024-icb-RS-2025_08.csv
Processando: /content/drive/MyDrive/dados/pda-024-icb-RS-2025_09.csv
Processando: /content/drive/MyDrive/dados/pda-024-icb-RS-2025_10.csv
Processando: /content/drive/MyDrive/dados/pda-024-icb-RS-2025_11.csv
Processando: /content/drive/MyDrive/dados/pda-024-icb-RS-2025_12.csv
Processando: /content/drive/MyDrive/dados/pda-024-icb-RS-2026_01.csv
Processando: /content/drive/MyDrive/dados/pda-024-icb-RS-2026_02.csv
Processando: /content/drive/MyDrive/dados/pda-024-icb-RS-2026_03.csv
Processando: /content/drive/MyDrive/dados/pda-024-icb-RS-2026_04.csv
Processando: /content/drive/MyDrive/dados/pda-024-icb-RS-2026_05.csv
Processando: /content/drive/MyDrive/dados/pda-024-icb-RS-2026_06.csv
Total de linhas após o filtro: 1667223

In [ ]:
# Coluna que contém a frequência (os números inteiros)
coluna_frequencia = 'QT_BENEFICIARIO_ATIVO'

# O df.index.repeat repete o índice de cada linha X vezes, baseado no valor da coluna
df_expandido = df_final.loc[df_final.index.repeat(df_final[coluna_frequencia])]

# Reseta o índice para ficar organizado (0, 1, 2, 3...)
df_expandido = df_expandido.reset_index(drop=True)

print(f"Total de linhas após expansão: {len(df_expandido)}")

Total de linhas após expansão: 13116041

In [ ]:
import pandas as pd

caminho_arquivo = '/content/drive/MyDrive/dados/dados_perfil_unimed_poa.csv'
df_perfil = pd.read_csv(caminho_arquivo)

print(f"DataFrame 'df_perfil' carregado com {len(df_perfil)} linhas e {len(df_perfil.columns)} colunas.")

/tmp/ipykernel_12183/4006837852.py:4: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df_perfil = pd.read_csv(caminho_arquivo)

DataFrame 'df_perfil' carregado com 13116041 linhas e 22 colunas.

In [ ]:
df_perfil.head(3)

,ID_CMPT_MOVEL,CD_OPERADORA,NM_RAZAO_SOCIAL,NR_CNPJ,MODALIDADE_OPERADORA,SG_UF,CD_MUNICIPIO,NM_MUNICIPIO,TP_SEXO,DE_FAIXA_ETARIA,...,TP_VIGENCIA_PLANO,DE_CONTRATACAO_PLANO,DE_SEGMENTACAO_PLANO,DE_ABRG_GEOGRAFICA_PLANO,COBERTURA_ASSIST_PLAN,TIPO_VINCULO,QT_BENEFICIARIO_ATIVO,QT_BENEFICIARIO_ADERIDO,QT_BENEFICIARIO_CANCELADO,DT_CARGA
0,2025-07,352501,UNIMED PORTO ALEGRE - COOPERATIVA MÃDICA LTDA.,"8,70966E+13",COOPERATIVA MÃDICA,RS,430920,GravataÃ­,F,50 a 54 anos,...,P,Individual ou Familiar,Ambulatorial + Hospitalar com obstetrÃ­cia,Nacional,MÃ©dico-hospitalar,Titular,3,0,0,17/07/2026
1,2025-07,352501,UNIMED PORTO ALEGRE - COOPERATIVA MÃDICA LTDA.,"8,70966E+13",COOPERATIVA MÃDICA,RS,430920,GravataÃ­,F,50 a 54 anos,...,P,Individual ou Familiar,Ambulatorial + Hospitalar com obstetrÃ­cia,Nacional,MÃ©dico-hospitalar,Titular,3,0,0,17/07/2026
2,2025-07,352501,UNIMED PORTO ALEGRE - COOPERATIVA MÃDICA LTDA.,"8,70966E+13",COOPERATIVA MÃDICA,RS,430920,GravataÃ­,F,50 a 54 anos,...,P,Individual ou Familiar,Ambulatorial + Hospitalar com obstetrÃ­cia,Nacional,MÃ©dico-hospitalar,Titular,3,0,0,17/07/2026

In [ ]:
# Salva o resultado final em um novo CSV
caminho_salvar = '/content/drive/MyDrive/dados/dados_perfil_unimed_poa.csv'
df_expandido.to_csv(caminho_salvar, index=False)
print("Arquivo salvo com sucesso!")

Arquivo salvo com sucesso!

In [ ]:
#recomeça do ponto anterior

In [ ]:
import pandas as pd

caminho_arquivo = '/content/drive/MyDrive/dados/dados_perfil_unimed_poa.csv'
df_perfil = pd.read_csv(caminho_arquivo)

print(f"DataFrame 'df_perfil' carregado com {len(df_perfil)} linhas e {len(df_perfil.columns)} colunas.")

/tmp/ipykernel_6274/4006837852.py:4: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df_perfil = pd.read_csv(caminho_arquivo)

DataFrame 'df_perfil' carregado com 13116041 linhas e 22 colunas.

In [ ]:
df_perfil.head(3)

,ID_CMPT_MOVEL,CD_OPERADORA,NM_RAZAO_SOCIAL,NR_CNPJ,MODALIDADE_OPERADORA,SG_UF,CD_MUNICIPIO,NM_MUNICIPIO,TP_SEXO,DE_FAIXA_ETARIA,...,TP_VIGENCIA_PLANO,DE_CONTRATACAO_PLANO,DE_SEGMENTACAO_PLANO,DE_ABRG_GEOGRAFICA_PLANO,COBERTURA_ASSIST_PLAN,TIPO_VINCULO,QT_BENEFICIARIO_ATIVO,QT_BENEFICIARIO_ADERIDO,QT_BENEFICIARIO_CANCELADO,DT_CARGA
0,2025-07,352501,UNIMED PORTO ALEGRE - COOPERATIVA MÃDICA LTDA.,"8,70966E+13",COOPERATIVA MÃDICA,RS,430920,GravataÃ­,F,50 a 54 anos,...,P,Individual ou Familiar,Ambulatorial + Hospitalar com obstetrÃ­cia,Nacional,MÃ©dico-hospitalar,Titular,3,0,0,17/07/2026
1,2025-07,352501,UNIMED PORTO ALEGRE - COOPERATIVA MÃDICA LTDA.,"8,70966E+13",COOPERATIVA MÃDICA,RS,430920,GravataÃ­,F,50 a 54 anos,...,P,Individual ou Familiar,Ambulatorial + Hospitalar com obstetrÃ­cia,Nacional,MÃ©dico-hospitalar,Titular,3,0,0,17/07/2026
2,2025-07,352501,UNIMED PORTO ALEGRE - COOPERATIVA MÃDICA LTDA.,"8,70966E+13",COOPERATIVA MÃDICA,RS,430920,GravataÃ­,F,50 a 54 anos,...,P,Individual ou Familiar,Ambulatorial + Hospitalar com obstetrÃ­cia,Nacional,MÃ©dico-hospitalar,Titular,3,0,0,17/07/2026

In [ ]:
columns_to_drop = ['CD_OPERADORA', 'NM_RAZAO_SOCIAL', 'NR_CNPJ', 'MODALIDADE_OPERADORA', 'SG_UF']
df_perfil.drop(columns=columns_to_drop, inplace=True)

print(f"Colunas removidas. O DataFrame 'df_perfil' agora tem {df_perfil.shape[1]} colunas.")

Colunas removidas. O DataFrame 'df_perfil' agora tem 17 colunas.

In [ ]:
# 1. Carregar o arquivo NIP.CSV e processá-lo
file_path = '/content/drive/MyDrive/dados/NIP.CSV'

try:
    # Carregar o arquivo com o separador e encoding identificados
    df_nip = pd.read_csv(file_path, sep=';', encoding='latin1', low_memory=False)

    # Renomear as colunas para facilitar o uso, tratando o BOM se presente
    # A string 'ï»¿Mês' pode vir como nome da coluna se o BOM não for tratado automaticamente
    df_nip.rename(columns={'ï»¿MÃªs': 'Mês', 'ReclamaÃ§Ãµes (NIP)': 'Reclamações'}, inplace=True)

    print(f"Arquivo NIP.CSV carregado com sucesso de '{file_path}'.")

except FileNotFoundError:
    print(f"Erro: O arquivo '{file_path}' não foi encontrado. Verifique o caminho.")
    df_nip = pd.DataFrame(columns=['Mês', 'Reclamações']) # Fallback
except Exception as e:
    print(f"Erro ao carregar ou processar NIP.CSV: {e}. Criando DataFrame vazio de fallback.")
    df_nip = pd.DataFrame(columns=['Mês', 'Reclamações']) # Fallback

print("Primeiras linhas de df_nip:")
display(df_nip.head())
print("Informações sobre df_nip:")
display(df_nip.info())

Arquivo NIP.CSV carregado com sucesso de '/content/drive/MyDrive/dados/NIP.CSV'.
Primeiras linhas de df_nip:

      Mês  Reclamações
0  jan/25           70
1  fev/25           55
2  mar/25           82
3  abr/25           97
4  mai/25          106

Informações sobre df_nip:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Mês          17 non-null     object
 1   Reclamações  17 non-null     int64
dtypes: int64(1), object(1)
memory usage: 404.0+ bytes

None

In [ ]:
# dicionário mês abreviado → número
meses = {
    "jan": "01", "fev": "02", "mar": "03", "abr": "04",
    "mai": "05", "jun": "06", "jul": "07", "ago": "08",
    "set": "09", "out": "10", "nov": "11", "dez": "12"
}

# cria nova coluna convertendo "jan/25" → "2025-01"
df_nip["mes_ano_iso"] = (
    df_nip["Mês"]
    .str.lower()
    .str.replace(
        r"(\w{3})/(\d{2})",
        lambda m: f"20{m.group(2)}-{meses[m.group(1)]}",
        regex=True
    )
)

In [ ]:
df_nip.head(3)

      Mês  Reclamações mes_ano_iso
0  jan/25           70     2025-01
1  fev/25           55     2025-02
2  mar/25           82     2025-03

In [ ]:
# Salva o resultado final em um novo CSV
caminho_salvar = '/content/drive/MyDrive/dados/dados_perfil_unimed_poa2.csv'
df_perfil.to_csv(caminho_salvar, index=False)
print("Arquivo salvo com sucesso!")

Arquivo salvo com sucesso!

# recomeço - etapa 3

In [ ]:
# baixar arquivo novamente caso necessário

In [ ]:
df_perfil = df_perfil.merge(
    df_nip[["mes_ano_iso", "Reclamações"]],
    left_on="ID_CMPT_MOVEL",
    right_on="mes_ano_iso",
    how="left"
)

In [ ]:
df_perfil.head(2)

,ID_CMPT_MOVEL,CD_MUNICIPIO,NM_MUNICIPIO,TP_SEXO,DE_FAIXA_ETARIA,DE_FAIXA_ETARIA_REAJ,CD_PLANO,TP_VIGENCIA_PLANO,DE_CONTRATACAO_PLANO,DE_SEGMENTACAO_PLANO,DE_ABRG_GEOGRAFICA_PLANO,COBERTURA_ASSIST_PLAN,TIPO_VINCULO,QT_BENEFICIARIO_ATIVO,QT_BENEFICIARIO_ADERIDO,QT_BENEFICIARIO_CANCELADO,DT_CARGA,mes_ano_iso,Reclamações
0,2025-07,430920,GravataÃ­,F,50 a 54 anos,54 a 58 anos,706470995,P,Individual ou Familiar,Ambulatorial + Hospitalar com obstetrÃ­cia,Nacional,MÃ©dico-hospitalar,Titular,3,0,0,17/07/2026,2025-07,90.0
1,2025-07,430920,GravataÃ­,F,50 a 54 anos,54 a 58 anos,706470995,P,Individual ou Familiar,Ambulatorial + Hospitalar com obstetrÃ­cia,Nacional,MÃ©dico-hospitalar,Titular,3,0,0,17/07/2026,2025-07,90.0

In [ ]:
import re
import numpy as np
import pandas as pd


def converter_faixa_etaria(valor):
  # Trata valores nulos ou inválidos ("Informada Incorr")
  if pd.isna(valor) or 'incorr' in str(valor).lower():
    return np.nan

  texto = str(valor).strip().lower()

  # Casos limites específicos
  if 'menos de 1' in texto:
    return 0.5
  if '80' in texto and 'mais' in texto:
    return 82.5  # Estimativa para a faixa aberta de 80+

  # Extrai os dois números da faixa (ex: "20 a 24 anos" -> [20, 24])
  numeros = re.findall(r'\d+', texto)
  if len(numeros) == 2:
    inicio, fim = float(numeros[0]), float(numeros[1])
    return (inicio + fim) / 2.0

  return np.nan


# Aplicação no seu DataFrame:
# A coluna de faixa etária no df_perfil é 'DE_FAIXA_ETARIA'
df_perfil['idade_ponto_medio'] = df_perfil['DE_FAIXA_ETARIA'].apply(converter_faixa_etaria)

In [ ]:
#salva estado atual - memória quase estourando, risco de perda do progresso

In [ ]:
# Salva o resultado final em um novo CSV
caminho_salvar = '/content/drive/MyDrive/dados/dados_perfil_unimed_poa3.csv'
df_perfil.to_csv(caminho_salvar, index=False)
print("Arquivo salvo com sucesso!")

Arquivo salvo com sucesso!

In [ ]:
import pandas as pd

caminho_arquivo = '/content/drive/MyDrive/dados/dados_perfil_unimed_poa3.csv'
df_perfil = pd.read_csv(caminho_arquivo)

print(f"DataFrame 'df_perfil' carregado com {len(df_perfil)} linhas e {len(df_perfil.columns)} colunas.")

/tmp/ipykernel_14602/2847983587.py:4: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  df_perfil = pd.read_csv(caminho_arquivo)

DataFrame 'df_perfil' carregado com 13116041 linhas e 20 colunas.

In [ ]:
df_perfil.head(2)

,ID_CMPT_MOVEL,CD_MUNICIPIO,NM_MUNICIPIO,TP_SEXO,DE_FAIXA_ETARIA,DE_FAIXA_ETARIA_REAJ,CD_PLANO,TP_VIGENCIA_PLANO,DE_CONTRATACAO_PLANO,DE_SEGMENTACAO_PLANO,DE_ABRG_GEOGRAFICA_PLANO,COBERTURA_ASSIST_PLAN,TIPO_VINCULO,QT_BENEFICIARIO_ATIVO,QT_BENEFICIARIO_ADERIDO,QT_BENEFICIARIO_CANCELADO,DT_CARGA,mes_ano_iso,Reclamações,idade_ponto_medio
0,2025-07,430920,GravataÃ­,F,50 a 54 anos,54 a 58 anos,706470995,P,Individual ou Familiar,Ambulatorial + Hospitalar com obstetrÃ­cia,Nacional,MÃ©dico-hospitalar,Titular,3,0,0,17/07/2026,2025-07,90.0,52.0
1,2025-07,430920,GravataÃ­,F,50 a 54 anos,54 a 58 anos,706470995,P,Individual ou Familiar,Ambulatorial + Hospitalar com obstetrÃ­cia,Nacional,MÃ©dico-hospitalar,Titular,3,0,0,17/07/2026,2025-07,90.0,52.0

In [ ]:
# Cria uma coluna numérica simples (1 para M, 0 para F/outros)
df_perfil['TP_SEXO_M'] = (df_perfil['TP_SEXO'].str.upper() == 'M').astype(int)

In [ ]:
df_perfil.head(1)

,ID_CMPT_MOVEL,CD_MUNICIPIO,NM_MUNICIPIO,TP_SEXO,DE_FAIXA_ETARIA,DE_FAIXA_ETARIA_REAJ,CD_PLANO,TP_VIGENCIA_PLANO,DE_CONTRATACAO_PLANO,DE_SEGMENTACAO_PLANO,...,COBERTURA_ASSIST_PLAN,TIPO_VINCULO,QT_BENEFICIARIO_ATIVO,QT_BENEFICIARIO_ADERIDO,QT_BENEFICIARIO_CANCELADO,DT_CARGA,mes_ano_iso,Reclamações,idade_ponto_medio,TP_SEXO_M
0,2025-07,430920,GravataÃ­,F,50 a 54 anos,54 a 58 anos,706470995,P,Individual ou Familiar,Ambulatorial + Hospitalar com obstetrÃ­cia,...,MÃ©dico-hospitalar,Titular,3,0,0,17/07/2026,2025-07,90.0,52.0,0

In [ ]:
colunas_planos = [
    'DE_CONTRATACAO_PLANO',
    'DE_SEGMENTACAO_PLANO',
    'DE_ABRG_GEOGRAFICA_PLANO',
    'COBERTURA_ASSIST_PLAN', # Nome da coluna corrigido
    'TIPO_VINCULO',
]

# Gera os dummies mantendo apenas N-1 colunas para cada variável
df_encoded = pd.get_dummies(
    df_perfil, columns=colunas_planos, drop_first=True, dtype=int
)

In [ ]:
# Salva o resultado final em um novo CSV
caminho_salvar = '/content/drive/MyDrive/dados/dados_perfil_unimed_poa4.csv'
df_perfil.to_csv(caminho_salvar, index=False)
print("Arquivo salvo com sucesso!")

Arquivo salvo com sucesso!

In [ ]:
#recomeçando
import pandas as pd

caminho_arquivo = '/content/drive/MyDrive/dados/dados_perfil_unimed_poa4.csv'
df_perfil = pd.read_csv(caminho_arquivo)

print(f"DataFrame 'df_perfil' carregado com {len(df_perfil)} linhas e {len(df_perfil.columns)} colunas.")

/tmp/ipykernel_22388/1362033145.py:5: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  df_perfil = pd.read_csv(caminho_arquivo)

DataFrame 'df_perfil' carregado com 13116041 linhas e 21 colunas.

In [ ]:
# Mantém os 10 municípios com mais registros e transforma os demais em 'Outros'
top_municipios = df_perfil['NM_MUNICIPIO'].value_counts().nlargest(10).index

df_perfil['NM_MUNICIPIO_agrupado'] = df_perfil['NM_MUNICIPIO'].apply(
    lambda x: x if x in top_municipios else 'Outros'
)

# Agora sim aplica o get_dummies na versão reduzida
df_perfil = pd.get_dummies(df_perfil, columns=['NM_MUNICIPIO_agrupado'], drop_first=True)

In [ ]:
# Salva o resultado final em um novo CSV
caminho_salvar = '/content/drive/MyDrive/dados/dados_perfil_unimed_poa5.csv'
df_perfil.to_csv(caminho_salvar, index=False)
print("Arquivo salvo com sucesso!")

Arquivo salvo com sucesso!